<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

//        DB::table("tea_types")->insert([
//            ['name' => 'Black'],
//            ['name' => 'Green'],
//            ['name' => 'Yellow'],
//            ['name' => 'Oolong'],
//            ['name' => 'White'],
//            ['name' => 'Puerh'],
//            ['name' => 'Matcha'],
//        ]);
//
//        DB::table("tea_origins")->insert([
//            ['name' => 'Assam'],
//            ['name' => 'Ceylon'],
//            ['name' => 'China'],
//            ['name' => 'Darjeeling'],
//            ['name' => 'Japan'],
//            ['name' => 'Kenya'],
//            ['name' => 'Nilgiri'],
//        ]);

        DB::table("tea")->insert([
            ['name' => 'Earl Grey Special', 'description' => 'Earl Grey Special is an attractive alternative for lovers of the classic Earl Grey, one of the most famous and appreciated blends in the world. A fragrant tea with a lot of personality, loved both by bergamot fans and lovers of floral teas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '323', 'ingredients' => 'Black Tea, orange peel, cornflower petals, lemongrass, Jasmine flowers, flavourings', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Pakistani', 'description' => 'Energising Chai-style blend with a hint of vanilla that sophisticates its character and makes it perfect for an introduction to the world of Chai flavours. The vanilla with its exquisite fragrance accompanies the intensity of the black tea and spices. Excellent with a touch of milk for a creamier taste. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '323', 'ingredients' => 'Black Tea, cinnamon, clove, cardamom, clove oil, vanilla, aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Christmas Black', 'description' => 'ChristmasTea Black, from the Tea Shop range of Christmas teas, is a blend with more than 20 years of history and is still made with the same recipe as always. When taken with milk, it enhances the delicious taste of marzipan much more. Black Tea is a mild stimulant that helps clear the mind and relax the muscles.', 'price' => '319', 'ingredients' => 'Black Tea, orange, ALMOND, cinnamon, apple, clove, cornflower petals, orange oil, aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Earl Grey Creme', 'description' => 'A suggestive alternative to lovers of our classic Earl Grey. A creamy tea, with a lot of personality, which is enhanced by adding milk. Earl Grey remains one of the most famous and consumed mixes in the world. Black Tea provides us with antioxidants and theine keep us active all day long.', 'price' => '325', 'ingredients' => 'Blend of two Black Teas and aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Earl Grey Royal', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '406', 'ingredients' => 'Blend of Black Teas (Darjeeling First Flush and Hunan China), aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Golden Dragon', 'description' => 'An exclusive, limited production Black Tea from Yuhang in southern China, an environment ideal for the cultivation of good quality tea due to the many rivers, fertile valleys and warm temperatures. The sprout and the first two leaves are carefully picked and carefully hand-rolled into a snail shape, which gives it a superior quality. Golden Dragon tea is also known in China as Hong Luo. Its name is given by its coiled appearance, the golden colour and the abundant sprouts. Its intense sweet and caramelised taste makes this tea a delicacy, ideal to enjoy between meals or to accompany foods without the need to add dairy products, vegetable drinks, lemon or sweeteners. Black tea is the variety of tea with the highest theine content. Theine is a natural stimulant that keeps you awake and clears your mind. Black teas attributes also include its diuretic and antioxidant effects.', 'price' => '712', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Vithanakande', 'description' => 'A delicious Black Tea of limited production and quality "Finest Broken Orange Pekoe Fanning Extra Special". With a pronounced ripe fruity flavour and a predominant tannic intensity. A natural stimulant for vitality and concentration. This tea comes from the New Vithanakande garden, located near Ratnapura, and is surrounded by the Sinharaja rainforest. Its altitude ensures high air purity and very propitious climatic conditions. The owners of this garden invented a new way to preserve the silvery tone of the shoot tips, preventing them from oxidising while the rest of the leaves do. Black tea is the most theine-rich variety of Camellia Sinensis. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears your mind. The high sprout content of this black tea boosts its antioxidant potential.', 'price' => '301', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
            ['name' => 'Nuwara Eliya', 'description' => 'Tea grown in highlands, that is, the plantations are about 2,000 meters above sea level. It has a delicate brown color, an exquisite taste and an unmistakable aroma. It is considered the most important tea in Sri Lanka. Mixed with lemon and sugar it is ideal for preparing a delicious Ice Tea. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '325', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
            ['name' => 'Irish Blend', 'description' => 'A perfect mix to start the day with vitality and energy. Its astringency, malty aroma, robust body and high content of theine make it suitable for morning consumption with a cloud of milk. Black Tea has a diuretic and antioxidant effect. In particular, the Black Teas from the region of Assam (India) are higher in theine and tannins. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body.', 'price' => '325', 'ingredients' => 'Blend of Black Teas from Assam, India', 'type_id' => '1', 'origin_id' => '1'],
            ['name' => 'Berry Fields', 'description' => 'Colorful mixture of Black Tea with wild fruit and beet. A real delight for breakfast and snacks. Its sweet and enveloping aroma offers versatility in hot or cold consumption, only, with milk or vegetable drink. A perfect base to prepare delicious and nutritious Smoothies. Consult our recipes in Youtube Tea Shop channel. Black Tea is a natural mild stimulant, which helps to clear the mind and relax the muscles. Red fruits along with beets are a source of vitamins and antioxidants.', 'price' => '367', 'ingredients' => 'Black Tea, apple, rose hip, beet, rose hip seeds, strawberry leaves, strawberry, blueberry, raspberry, elder, redcurrant, aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Earl Grey Superior', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the "five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '345', 'ingredients' => 'Black tea, natural lemon flavouring and aroma', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Vanilla Black', 'description' => 'The elegant flavor of the vanilla "bourbon" nuances the astringency of the Black Tea. Perfect for breakfast and after lunch. Helps to keep up with the day. Black Tea is the one that contributes more theine of all the varieties of tea. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '343', 'ingredients' => 'Black Tea, vanilla, aroma.', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Golden Yunnan', 'description' => 'Chinese Black Tea of exceptional quality, composed only of golden shoots. A slightly earthy taste with notes that reminiscent us of black truffle. A strong aroma with a lot of character, of delicate and silky astringency. Its limited production gives it even more prestige. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect. We recommend that it be kept protected from light and humidity and at a temperature between 7°C and 20°C.', 'price' => '355', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Formosa Tarry Lapsang', 'description' => 'It is distinguished by its smoky flavour and aroma, which is often enjoyed as an accompaniment with fish dishes and as a complement to meals. Traditionally, the smoking method is done by drying the tea leaves over a pine or cypress wood fire to give it an aroma and flavour without astringency. This method was born as a quick drying method. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '436', 'ingredients' => 'Smoked Lapsang Souchong Black Tea', 'type_id' => '1', 'origin_id' => '3'],
            ['name' => 'Mini Tuocha', 'description' => 'Tea from Yunnan, in south-east China, where this speciality was born. Tuo Cha literally means birds nest (tuo) of tea (cha). It has this particular shape because at one stage of the production process it is pressed in a specific mould in different sizes and weights. Its level of theine is more moderate when it is used in unbroken unit form, or higher when it is broken, as theine is more soluble. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears the mind. This particular quality of Black Toucha is composed of whole leaves and sprouts, which increases the antioxidant potential. A tea with a full body and fragrance in line with the black teas of this area, with a medium astringency and sweet aromatic notes and a slightly smoky, cocoa-like air. The pressed shape ensures a better preservation over time and easier transport. Each unit weighs approximately 5 g and is individually wrapped in bamboo fibre paper. One unit of mini Tuocha can be used to make a Super Jumbo cup or a small 500 ml teapot, depending on the desired strength. ', 'price' => '181', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
            ]);
//
//        DB::table("tea_images")->insert([
//            ['name' => '10113_EarlGreySpecial_1000x1000_l.jpg', 'tea_id' => '1'],
//
//            ['name' => '10109_Pakistani_1000x1000_l.jpg', 'tea_id' => '2'],
//            ['name' => 'te-engro-pakistani-1000x1000.jpg', 'tea_id' => '2'],
//
//            ['name' => '10142_ChristmasTeaBlack_1000x1000_l.jpg', 'tea_id' => '3'],
//            ['name' => 'Te-n-2-xmas-black-1000x1000.jpg', 'tea_id' => '3'],
//
//            ['name' => '10137_EarlGreyCreme_1000x1000_l.jpg', 'tea_id' => '4'],
//            ['name' => '10111_EarlGreyRoyal_1000x1000_l.jpg', 'tea_id' => '5'],
//            ['name' => '10059_GoldenDragonBlackTeaChina_1000X1000_l-.jpg', 'tea_id' => '6'],
//            ['name' => 'CeylonFbopfexsNewWithanakande_1000X1000_l-1.jpg', 'tea_id' => '7'],
//            ['name' => '10011_CeylonNuwaraEliyaBattalgallaOP_1000x1000_l.jpg', 'tea_id' => '8'],
//            ['name' => '10004_IrishBlend_1000x1000_l.jpg', 'tea_id' => '9'],
//            ['name' => '10153_BerryFields_1000x1000_l.jpg', 'tea_id' => '10'],
//            ['name' => '10112_EarlGreySuperior_1000x1000_l.jpg', 'tea_id' => '11'],
//            ['name' => '10110_VanillaBlackTea_1000x1000_l.jpg', 'tea_id' => '12'],
//            ['name' => '10052_GoldenYunnanFinesTippy_418X418_l-1.jpg', 'tea_id' => '13'],
//            ['name' => '10040_FormosaTarryLapsangSouchong_1000x1000_l.jpg', 'tea_id' => '14'],
//            ['name' => '10058_ChinaBlackMiniTuocha_1000X1000_l-.jpg', 'tea_id' => '15'],
//        ]);
//
//        DB::table("tea")->insert([
//            ['name' => 'Earl Grey Special', 'description' => 'Earl Grey Special is an attractive alternative for lovers of the classic Earl Grey, one of the most famous and appreciated blends in the world. A fragrant tea with a lot of personality, loved both by bergamot fans and lovers of floral teas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '323', 'ingredients' => 'Black Tea, orange peel, cornflower petals, lemongrass, Jasmine flowers, flavourings', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Pakistani', 'description' => 'Energising Chai-style blend with a hint of vanilla that sophisticates its character and makes it perfect for an introduction to the world of Chai flavours. The vanilla with its exquisite fragrance accompanies the intensity of the black tea and spices. Excellent with a touch of milk for a creamier taste. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '323', 'ingredients' => 'Black Tea, cinnamon, clove, cardamom, clove oil, vanilla, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Christmas Black', 'description' => 'ChristmasTea Black, from the Tea Shop range of Christmas teas, is a blend with more than 20 years of history and is still made with the same recipe as always. When taken with milk, it enhances the delicious taste of marzipan much more. Black Tea is a mild stimulant that helps clear the mind and relax the muscles.', 'price' => '319', 'ingredients' => 'Black Tea, orange, ALMOND, cinnamon, apple, clove, cornflower petals, orange oil, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Creme', 'description' => 'A suggestive alternative to lovers of our classic Earl Grey. A creamy tea, with a lot of personality, which is enhanced by adding milk. Earl Grey remains one of the most famous and consumed mixes in the world. Black Tea provides us with antioxidants and theine keep us active all day long.', 'price' => '325', 'ingredients' => 'Blend of two Black Teas and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Royal', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '406', 'ingredients' => 'Blend of Black Teas (Darjeeling First Flush and Hunan China), aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Dragon', 'description' => 'An exclusive, limited production Black Tea from Yuhang in southern China, an environment ideal for the cultivation of good quality tea due to the many rivers, fertile valleys and warm temperatures. The sprout and the first two leaves are carefully picked and carefully hand-rolled into a snail shape, which gives it a superior quality. Golden Dragon tea is also known in China as Hong Luo. Its name is given by its coiled appearance, the golden colour and the abundant sprouts. Its intense sweet and caramelised taste makes this tea a delicacy, ideal to enjoy between meals or to accompany foods without the need to add dairy products, vegetable drinks, lemon or sweeteners. Black tea is the variety of tea with the highest theine content. Theine is a natural stimulant that keeps you awake and clears your mind. Black teas attributes also include its diuretic and antioxidant effects.', 'price' => '712', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vithanakande', 'description' => 'A delicious Black Tea of limited production and quality "Finest Broken Orange Pekoe Fanning Extra Special". With a pronounced ripe fruity flavour and a predominant tannic intensity. A natural stimulant for vitality and concentration. This tea comes from the New Vithanakande garden, located near Ratnapura, and is surrounded by the Sinharaja rainforest. Its altitude ensures high air purity and very propitious climatic conditions. The owners of this garden invented a new way to preserve the silvery tone of the shoot tips, preventing them from oxidising while the rest of the leaves do. Black tea is the most theine-rich variety of Camellia Sinensis. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears your mind. The high sprout content of this black tea boosts its antioxidant potential.', 'price' => '301', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Nuwara Eliya', 'description' => 'Tea grown in highlands, that is, the plantations are about 2,000 meters above sea level. It has a delicate brown color, an exquisite taste and an unmistakable aroma. It is considered the most important tea in Sri Lanka. Mixed with lemon and sugar it is ideal for preparing a delicious Ice Tea. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '325', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Irish Blend', 'description' => 'A perfect mix to start the day with vitality and energy. Its astringency, malty aroma, robust body and high content of theine make it suitable for morning consumption with a cloud of milk. Black Tea has a diuretic and antioxidant effect. In particular, the Black Teas from the region of Assam (India) are higher in theine and tannins. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body.', 'price' => '325', 'ingredients' => 'Blend of Black Teas from Assam, India', 'type_id' => '1', 'origin_id' => '1'],
//            ['name' => 'Berry Fields', 'description' => 'Colorful mixture of Black Tea with wild fruit and beet. A real delight for breakfast and snacks. Its sweet and enveloping aroma offers versatility in hot or cold consumption, only, with milk or vegetable drink. A perfect base to prepare delicious and nutritious Smoothies. Consult our recipes in Youtube Tea Shop channel. Black Tea is a natural mild stimulant, which helps to clear the mind and relax the muscles. Red fruits along with beets are a source of vitamins and antioxidants.', 'price' => '367', 'ingredients' => 'Black Tea, apple, rose hip, beet, rose hip seeds, strawberry leaves, strawberry, blueberry, raspberry, elder, redcurrant, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Superior', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the "five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '345', 'ingredients' => 'Black tea, natural lemon flavouring and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vanilla Black', 'description' => 'The elegant flavor of the vanilla "bourbon" nuances the astringency of the Black Tea. Perfect for breakfast and after lunch. Helps to keep up with the day. Black Tea is the one that contributes more theine of all the varieties of tea. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '343', 'ingredients' => 'Black Tea, vanilla, aroma.', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Yunnan', 'description' => 'Chinese Black Tea of exceptional quality, composed only of golden shoots. A slightly earthy taste with notes that reminiscent us of black truffle. A strong aroma with a lot of character, of delicate and silky astringency. Its limited production gives it even more prestige. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect. We recommend that it be kept protected from light and humidity and at a temperature between 7°C and 20°C.', 'price' => '355', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Formosa Tarry Lapsang', 'description' => 'It is distinguished by its smoky flavour and aroma, which is often enjoyed as an accompaniment with fish dishes and as a complement to meals. Traditionally, the smoking method is done by drying the tea leaves over a pine or cypress wood fire to give it an aroma and flavour without astringency. This method was born as a quick drying method. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '436', 'ingredients' => 'Smoked Lapsang Souchong Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Mini Tuocha', 'description' => 'Tea from Yunnan, in south-east China, where this speciality was born. Tuo Cha literally means birds nest (tuo) of tea (cha). It has this particular shape because at one stage of the production process it is pressed in a specific mould in different sizes and weights. Its level of theine is more moderate when it is used in unbroken unit form, or higher when it is broken, as theine is more soluble. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears the mind. This particular quality of Black Toucha is composed of whole leaves and sprouts, which increases the antioxidant potential. A tea with a full body and fragrance in line with the black teas of this area, with a medium astringency and sweet aromatic notes and a slightly smoky, cocoa-like air. The pressed shape ensures a better preservation over time and easier transport. Each unit weighs approximately 5 g and is individually wrapped in bamboo fibre paper. One unit of mini Tuocha can be used to make a Super Jumbo cup or a small 500 ml teapot, depending on the desired strength. ', 'price' => '181', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//        ]);
////
    }
}
