<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

//        DB::table("tea_types")->insert([
//            ['name' => 'Black'],
//            ['name' => 'Green'],
//            ['name' => 'Yellow'],
//            ['name' => 'Oolong'],
//            ['name' => 'White'],
//            ['name' => 'Puerh'],
//            ['name' => 'Matcha'],
//        ]);
//
//        DB::table("tea_origins")->insert([
//            ['name' => 'Assam'],
//            ['name' => 'Ceylon'],
//            ['name' => 'China'],
//            ['name' => 'Darjeeling'],
//            ['name' => 'Japan'],
//            ['name' => 'Kenya'],
//            ['name' => 'Nilgiri'],
//        ]);

//        DB::table("tea")->insert([
//            ['name' => 'Earl Grey Special', 'description' => 'Earl Grey Special is an attractive alternative for lovers of the classic Earl Grey, one of the most famous and appreciated blends in the world. A fragrant tea with a lot of personality, loved both by bergamot fans and lovers of floral teas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '323', 'ingredients' => 'Black Tea, orange peel, cornflower petals, lemongrass, Jasmine flowers, flavourings', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Pakistani', 'description' => 'Energising Chai-style blend with a hint of vanilla that sophisticates its character and makes it perfect for an introduction to the world of Chai flavours. The vanilla with its exquisite fragrance accompanies the intensity of the black tea and spices. Excellent with a touch of milk for a creamier taste. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '323', 'ingredients' => 'Black Tea, cinnamon, clove, cardamom, clove oil, vanilla, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Christmas Black', 'description' => 'ChristmasTea Black, from the Tea Shop range of Christmas teas, is a blend with more than 20 years of history and is still made with the same recipe as always. When taken with milk, it enhances the delicious taste of marzipan much more. Black Tea is a mild stimulant that helps clear the mind and relax the muscles.', 'price' => '319', 'ingredients' => 'Black Tea, orange, ALMOND, cinnamon, apple, clove, cornflower petals, orange oil, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Creme', 'description' => 'A suggestive alternative to lovers of our classic Earl Grey. A creamy tea, with a lot of personality, which is enhanced by adding milk. Earl Grey remains one of the most famous and consumed mixes in the world. Black Tea provides us with antioxidants and theine keep us active all day long.', 'price' => '325', 'ingredients' => 'Blend of two Black Teas and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Royal', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '406', 'ingredients' => 'Blend of Black Teas (Darjeeling First Flush and Hunan China), aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Dragon', 'description' => 'An exclusive, limited production Black Tea from Yuhang in southern China, an environment ideal for the cultivation of good quality tea due to the many rivers, fertile valleys and warm temperatures. The sprout and the first two leaves are carefully picked and carefully hand-rolled into a snail shape, which gives it a superior quality. Golden Dragon tea is also known in China as Hong Luo. Its name is given by its coiled appearance, the golden colour and the abundant sprouts. Its intense sweet and caramelised taste makes this tea a delicacy, ideal to enjoy between meals or to accompany foods without the need to add dairy products, vegetable drinks, lemon or sweeteners. Black tea is the variety of tea with the highest theine content. Theine is a natural stimulant that keeps you awake and clears your mind. Black teas attributes also include its diuretic and antioxidant effects.', 'price' => '712', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vithanakande', 'description' => 'A delicious Black Tea of limited production and quality "Finest Broken Orange Pekoe Fanning Extra Special". With a pronounced ripe fruity flavour and a predominant tannic intensity. A natural stimulant for vitality and concentration. This tea comes from the New Vithanakande garden, located near Ratnapura, and is surrounded by the Sinharaja rainforest. Its altitude ensures high air purity and very propitious climatic conditions. The owners of this garden invented a new way to preserve the silvery tone of the shoot tips, preventing them from oxidising while the rest of the leaves do. Black tea is the most theine-rich variety of Camellia Sinensis. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears your mind. The high sprout content of this black tea boosts its antioxidant potential.', 'price' => '301', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Nuwara Eliya', 'description' => 'Tea grown in highlands, that is, the plantations are about 2,000 meters above sea level. It has a delicate brown color, an exquisite taste and an unmistakable aroma. It is considered the most important tea in Sri Lanka. Mixed with lemon and sugar it is ideal for preparing a delicious Ice Tea. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '325', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Irish Blend', 'description' => 'A perfect mix to start the day with vitality and energy. Its astringency, malty aroma, robust body and high content of theine make it suitable for morning consumption with a cloud of milk. Black Tea has a diuretic and antioxidant effect. In particular, the Black Teas from the region of Assam (India) are higher in theine and tannins. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body.', 'price' => '325', 'ingredients' => 'Blend of Black Teas from Assam, India', 'type_id' => '1', 'origin_id' => '1'],
//            ['name' => 'Berry Fields', 'description' => 'Colorful mixture of Black Tea with wild fruit and beet. A real delight for breakfast and snacks. Its sweet and enveloping aroma offers versatility in hot or cold consumption, only, with milk or vegetable drink. A perfect base to prepare delicious and nutritious Smoothies. Consult our recipes in Youtube Tea Shop channel. Black Tea is a natural mild stimulant, which helps to clear the mind and relax the muscles. Red fruits along with beets are a source of vitamins and antioxidants.', 'price' => '367', 'ingredients' => 'Black Tea, apple, rose hip, beet, rose hip seeds, strawberry leaves, strawberry, blueberry, raspberry, elder, redcurrant, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Superior', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the "five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '345', 'ingredients' => 'Black tea, natural lemon flavouring and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vanilla Black', 'description' => 'The elegant flavor of the vanilla "bourbon" nuances the astringency of the Black Tea. Perfect for breakfast and after lunch. Helps to keep up with the day. Black Tea is the one that contributes more theine of all the varieties of tea. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '343', 'ingredients' => 'Black Tea, vanilla, aroma.', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Yunnan', 'description' => 'Chinese Black Tea of exceptional quality, composed only of golden shoots. A slightly earthy taste with notes that reminiscent us of black truffle. A strong aroma with a lot of character, of delicate and silky astringency. Its limited production gives it even more prestige. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect. We recommend that it be kept protected from light and humidity and at a temperature between 7°C and 20°C.', 'price' => '355', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Formosa Tarry Lapsang', 'description' => 'It is distinguished by its smoky flavour and aroma, which is often enjoyed as an accompaniment with fish dishes and as a complement to meals. Traditionally, the smoking method is done by drying the tea leaves over a pine or cypress wood fire to give it an aroma and flavour without astringency. This method was born as a quick drying method. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '436', 'ingredients' => 'Smoked Lapsang Souchong Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Mini Tuocha', 'description' => 'Tea from Yunnan, in south-east China, where this speciality was born. Tuo Cha literally means birds nest (tuo) of tea (cha). It has this particular shape because at one stage of the production process it is pressed in a specific mould in different sizes and weights. Its level of theine is more moderate when it is used in unbroken unit form, or higher when it is broken, as theine is more soluble. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears the mind. This particular quality of Black Toucha is composed of whole leaves and sprouts, which increases the antioxidant potential. A tea with a full body and fragrance in line with the black teas of this area, with a medium astringency and sweet aromatic notes and a slightly smoky, cocoa-like air. The pressed shape ensures a better preservation over time and easier transport. Each unit weighs approximately 5 g and is individually wrapped in bamboo fibre paper. One unit of mini Tuocha can be used to make a Super Jumbo cup or a small 500 ml teapot, depending on the desired strength. ', 'price' => '181', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//            ]);
//
//        DB::table("tea_images")->insert([
//            ['name' => '10113_EarlGreySpecial_1000x1000_l.jpg', 'tea_id' => '1'],
//
//            ['name' => '10109_Pakistani_1000x1000_l.jpg', 'tea_id' => '2'],
//            ['name' => 'te-engro-pakistani-1000x1000.jpg', 'tea_id' => '2'],
//
//            ['name' => '10142_ChristmasTeaBlack_1000x1000_l.jpg', 'tea_id' => '3'],
//            ['name' => 'Te-n-2-xmas-black-1000x1000.jpg', 'tea_id' => '3'],
//
//            ['name' => '10137_EarlGreyCreme_1000x1000_l.jpg', 'tea_id' => '4'],
//            ['name' => '10111_EarlGreyRoyal_1000x1000_l.jpg', 'tea_id' => '5'],
//            ['name' => '10059_GoldenDragonBlackTeaChina_1000X1000_l-.jpg', 'tea_id' => '6'],
//            ['name' => 'CeylonFbopfexsNewWithanakande_1000X1000_l-1.jpg', 'tea_id' => '7'],
//            ['name' => '10011_CeylonNuwaraEliyaBattalgallaOP_1000x1000_l.jpg', 'tea_id' => '8'],
//            ['name' => '10004_IrishBlend_1000x1000_l.jpg', 'tea_id' => '9'],
//            ['name' => '10153_BerryFields_1000x1000_l.jpg', 'tea_id' => '10'],
//            ['name' => '10112_EarlGreySuperior_1000x1000_l.jpg', 'tea_id' => '11'],
//            ['name' => '10110_VanillaBlackTea_1000x1000_l.jpg', 'tea_id' => '12'],
//            ['name' => '10052_GoldenYunnanFinesTippy_418X418_l-1.jpg', 'tea_id' => '13'],
//            ['name' => '10040_FormosaTarryLapsangSouchong_1000x1000_l.jpg', 'tea_id' => '14'],
//            ['name' => '10058_ChinaBlackMiniTuocha_1000X1000_l-.jpg', 'tea_id' => '15'],
//        ]);
//
//        DB::table("tea")->insert([
//            ['name' => 'Earl Grey Special', 'description' => 'Earl Grey Special is an attractive alternative for lovers of the classic Earl Grey, one of the most famous and appreciated blends in the world. A fragrant tea with a lot of personality, loved both by bergamot fans and lovers of floral teas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '323', 'ingredients' => 'Black Tea, orange peel, cornflower petals, lemongrass, Jasmine flowers, flavourings', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Pakistani', 'description' => 'Energising Chai-style blend with a hint of vanilla that sophisticates its character and makes it perfect for an introduction to the world of Chai flavours. The vanilla with its exquisite fragrance accompanies the intensity of the black tea and spices. Excellent with a touch of milk for a creamier taste. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '323', 'ingredients' => 'Black Tea, cinnamon, clove, cardamom, clove oil, vanilla, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Christmas Black', 'description' => 'ChristmasTea Black, from the Tea Shop range of Christmas teas, is a blend with more than 20 years of history and is still made with the same recipe as always. When taken with milk, it enhances the delicious taste of marzipan much more. Black Tea is a mild stimulant that helps clear the mind and relax the muscles.', 'price' => '319', 'ingredients' => 'Black Tea, orange, ALMOND, cinnamon, apple, clove, cornflower petals, orange oil, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Creme', 'description' => 'A suggestive alternative to lovers of our classic Earl Grey. A creamy tea, with a lot of personality, which is enhanced by adding milk. Earl Grey remains one of the most famous and consumed mixes in the world. Black Tea provides us with antioxidants and theine keep us active all day long.', 'price' => '325', 'ingredients' => 'Blend of two Black Teas and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Royal', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '406', 'ingredients' => 'Blend of Black Teas (Darjeeling First Flush and Hunan China), aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Dragon', 'description' => 'An exclusive, limited production Black Tea from Yuhang in southern China, an environment ideal for the cultivation of good quality tea due to the many rivers, fertile valleys and warm temperatures. The sprout and the first two leaves are carefully picked and carefully hand-rolled into a snail shape, which gives it a superior quality. Golden Dragon tea is also known in China as Hong Luo. Its name is given by its coiled appearance, the golden colour and the abundant sprouts. Its intense sweet and caramelised taste makes this tea a delicacy, ideal to enjoy between meals or to accompany foods without the need to add dairy products, vegetable drinks, lemon or sweeteners. Black tea is the variety of tea with the highest theine content. Theine is a natural stimulant that keeps you awake and clears your mind. Black teas attributes also include its diuretic and antioxidant effects.', 'price' => '712', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vithanakande', 'description' => 'A delicious Black Tea of limited production and quality "Finest Broken Orange Pekoe Fanning Extra Special". With a pronounced ripe fruity flavour and a predominant tannic intensity. A natural stimulant for vitality and concentration. This tea comes from the New Vithanakande garden, located near Ratnapura, and is surrounded by the Sinharaja rainforest. Its altitude ensures high air purity and very propitious climatic conditions. The owners of this garden invented a new way to preserve the silvery tone of the shoot tips, preventing them from oxidising while the rest of the leaves do. Black tea is the most theine-rich variety of Camellia Sinensis. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears your mind. The high sprout content of this black tea boosts its antioxidant potential.', 'price' => '301', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Nuwara Eliya', 'description' => 'Tea grown in highlands, that is, the plantations are about 2,000 meters above sea level. It has a delicate brown color, an exquisite taste and an unmistakable aroma. It is considered the most important tea in Sri Lanka. Mixed with lemon and sugar it is ideal for preparing a delicious Ice Tea. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '325', 'ingredients' => 'Black Tea', 'type_id' => '1', 'origin_id' => '2'],
//            ['name' => 'Irish Blend', 'description' => 'A perfect mix to start the day with vitality and energy. Its astringency, malty aroma, robust body and high content of theine make it suitable for morning consumption with a cloud of milk. Black Tea has a diuretic and antioxidant effect. In particular, the Black Teas from the region of Assam (India) are higher in theine and tannins. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body.', 'price' => '325', 'ingredients' => 'Blend of Black Teas from Assam, India', 'type_id' => '1', 'origin_id' => '1'],
//            ['name' => 'Berry Fields', 'description' => 'Colorful mixture of Black Tea with wild fruit and beet. A real delight for breakfast and snacks. Its sweet and enveloping aroma offers versatility in hot or cold consumption, only, with milk or vegetable drink. A perfect base to prepare delicious and nutritious Smoothies. Consult our recipes in Youtube Tea Shop channel. Black Tea is a natural mild stimulant, which helps to clear the mind and relax the muscles. Red fruits along with beets are a source of vitamins and antioxidants.', 'price' => '367', 'ingredients' => 'Black Tea, apple, rose hip, beet, rose hip seeds, strawberry leaves, strawberry, blueberry, raspberry, elder, redcurrant, aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Earl Grey Superior', 'description' => 'One of the most famous and consumed blends in the world. This famous blend is attributed to the English Count Charles Grey and was served in the "five oclock tea of the European nobility. Bergamot is a very exclusive Mediterranean citrus and its essence has always been highly sought after. Its delicate perfume is classified within the range of floral aromas. Black Tea provides us with antioxidants and theine helps us to keep us active all day long.', 'price' => '345', 'ingredients' => 'Black tea, natural lemon flavouring and aroma', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Vanilla Black', 'description' => 'The elegant flavor of the vanilla "bourbon" nuances the astringency of the Black Tea. Perfect for breakfast and after lunch. Helps to keep up with the day. Black Tea is the one that contributes more theine of all the varieties of tea. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect.', 'price' => '343', 'ingredients' => 'Black Tea, vanilla, aroma.', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Golden Yunnan', 'description' => 'Chinese Black Tea of exceptional quality, composed only of golden shoots. A slightly earthy taste with notes that reminiscent us of black truffle. A strong aroma with a lot of character, of delicate and silky astringency. Its limited production gives it even more prestige. Black Tea is the most theine of all tea varieties. Theine is a natural stimulant that relaxes the muscles, keeps the body and mind awake. It has a diuretic and antioxidant effect. We recommend that it be kept protected from light and humidity and at a temperature between 7°C and 20°C.', 'price' => '355', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Formosa Tarry Lapsang', 'description' => 'It is distinguished by its smoky flavour and aroma, which is often enjoyed as an accompaniment with fish dishes and as a complement to meals. Traditionally, the smoking method is done by drying the tea leaves over a pine or cypress wood fire to give it an aroma and flavour without astringency. This method was born as a quick drying method. Theine is a natural stimulant that relaxes the muscles, clears the mind and awakens the body. It has a diuretic and antioxidant effect.', 'price' => '436', 'ingredients' => 'Smoked Lapsang Souchong Black Tea', 'type_id' => '1', 'origin_id' => '3'],
//            ['name' => 'Mini Tuocha', 'description' => 'Tea from Yunnan, in south-east China, where this speciality was born. Tuo Cha literally means birds nest (tuo) of tea (cha). It has this particular shape because at one stage of the production process it is pressed in a specific mould in different sizes and weights. Its level of theine is more moderate when it is used in unbroken unit form, or higher when it is broken, as theine is more soluble. Theine is a natural stimulant that relaxes muscles, keeps you awake and clears the mind. This particular quality of Black Toucha is composed of whole leaves and sprouts, which increases the antioxidant potential. A tea with a full body and fragrance in line with the black teas of this area, with a medium astringency and sweet aromatic notes and a slightly smoky, cocoa-like air. The pressed shape ensures a better preservation over time and easier transport. Each unit weighs approximately 5 g and is individually wrapped in bamboo fibre paper. One unit of mini Tuocha can be used to make a Super Jumbo cup or a small 500 ml teapot, depending on the desired strength. ', 'price' => '181', 'ingredients' => 'Black Tea from Yunnan, China', 'type_id' => '1', 'origin_id' => '3'],
//        ]);
////
///
//        DB::table("tea")->insert([
//            ['name' => 'Magic Kingdom', 'description' => 'A tea to enjoy at breakfast, brunch or snacks, alone or with a vegetable drink. Its flavour is inspired by the traditional Roscón de Reyes, a delicious roll in the shape of a doughnut, which is usually decorated with candied fruit and is eaten on 6 January to celebrate the arrival of the Three Kings. The sweet complement to winter days that will please all palates. As well as being a treat, it is a delicious way to help digestion and stay hydrated. Young Green Tea perfumed with natural antioxidants. Jasmine flowers are a natural digestive and soothing.', 'price' => '346', 'ingredients' => 'Green tea, Oolong tea, carob, sultanas, anise, orange, pineapple, mango, barley grass, sunflower petals, cats foot flower, amaranth, cherries and aroma', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Ginger Citrus', 'description' => 'A unique blend that delights the most varied palates, both for lovers of sweet citrus, who seek the freshness of ginger, or for those who prefer the more herbal flavors of mate; all without dispensing with a rich source of antioxidants. Mate provides our body with energetic properties that help combat mental fatigue, while ginger acts to promote digestion.', 'price' => '447', 'ingredients' => 'Green Tea, green mate, ginger, matcha and aromas', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Beauty Guarana', 'description' => 'The splendor of Pitaya and Guarana mixes with green tea giving a sweet and floral cup for a contribution of antioxidants. A mix with an extra vitality. Its flavor can captivate lovers of floral and sweet flavors. Green tea base provides antioxidants. Guarana seeds contain caffeine and help reduce mental fatigue and promote immunity.', 'price' => '406', 'ingredients' => 'Green Tea, apple, pineapple (pineapple, sugar), dragon fruit, guarana seeds, cornflower petals and natural aromas', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Jasmine Dragon Pearls', 'description' => 'Its attractive taste attracts lovers of pure, sweet or floral teas. Its pearl shape has been handmade for over 100 years. The buds and leaves are carefully and meticulously handled to the perfect shape. This tea is made during the summer season. It allows three infusions (5 minutes at 70º the first one, the next two 2 minutes at 70º.) and it is important to note that after each infusion the theine decreases considerably. An ideal tea to drink hot with meals. Green Tea is an antioxidant and diuretic. Jasmine perfume is a good digestive and natural soothing.', 'price' => '561', 'ingredients' => 'Green Tea', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Jasmine Chung Feng', 'description' => 'The complex process of scented tea is an aromatic dream, and the high quantity of silvery sprouts gives it personality and delicacy. In the north of China it is tradition to serve jasmine tea as a welcoming gesture to guests. This tea can be infused twice, the first time for 3 minutes and the second infusion for 2 minutes.', 'price' => '1019', 'ingredients' => 'Organic Green Tea scented with jasmine flowers.', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Lung Ching Second Grade', 'description' => 'Lung Ching is also known as LongJing or Dragon Well Tea. It is a variety of green tea that is roasted and characterized by its tender and whole leaves, with a very uniform appearance and very low oxidation. It is produced in the Longjing Village area in Hangzhou, known for its high quality teas. The leaves of 2nd grade have an approximate size of 2 to 3 cm and define the quality of the teas as well as the certified production area does. It is a tea of delicate sweet almond flavor that leaves an infusion of jade green color. A delight for those who love delicate and smooth flavors. High quality pure Green Tea, a great natural antioxidant.', 'price' => '449', 'ingredients' => 'Green Tea from Longjing Village', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Organic Gunpowder', 'description' => 'The tea liqueur in this Gunpowder Organic is dense and intensely roasted. The leaves expand, releasing all their aromatic essence. Because of these characteristics it is used in Morocco to prepare mint tea. Its roasted and slightly bitter taste goes very well with any sweetener. Green Tea is especially diuretic and antioxidant. Due to its rolled form, within the range of green teas, it is among those with more theine.', 'price' => '347', 'ingredients' => 'Organic pure Green Tea from China.', 'type_id' => '2', 'origin_id' => '3'],
//            ['name' => 'Magic Mango', 'description' => 'Blend with Superfood ingredients. Moringa is an ingredient that contributes to improving the immune system. Its slightly bitter taste balances the sweet taste of Green Tea and mango. Both for its attractive taste and for its versatility, it can be consumed cold and hot, becoming an essential drink in the pantry. Mixture with strong antioxidant power thanks to Green Tea.', 'price' => '406', 'ingredients' => 'Green Tea, apple, mango, calendula petals, moringa, aroma', 'type_id' => '2', 'origin_id' => '5'],
//            ['name' => 'Genmaicha', 'description' => 'Very popular traditional Japanese green tea, with toasted rice and puffed rice. Its unique roasted and slightly salty taste makes it ideal to accompany meals. When hot, its aroma is enhanced and it also helps digestion. In England it is colloquially known as the "Pop Corn" Tea. It can also be consumed by adding Matcha, thus intensifying its flavor and properties. The Genmaicha identifies Japanese culture, tea and rice. It is the tea that is usually accompanied in the meals, which served very hot, is an ally for the digestion.', 'price' => '406', 'ingredients' => 'Green Tea from Japan with toasted rice and puffed rice', 'type_id' => '2', 'origin_id' => '5'],
//            ['name' => 'Japan Hojicha', 'description' => 'One of the most widely consumed green teas in Japanese culture, with a characteristic roasted and sweet taste with notes of cocoa, smooth and with very low astringency. For its production, the leaves and stems of Bancha Green Tea are selected, which, after roasting, turn from a bright green colour to a brownish tone. This process removes a large amount of theine and tannins. An irresistible for lovers of earthy flavours such as Pu Erh Red Tea and smooth flavours such as Oolong Tea, as well as for those seeking an alternative to the vegetal flavours characteristic of Japanese green teas.', 'price' => '345', 'ingredients' => 'Bio Green Tea', 'type_id' => '2', 'origin_id' => '5'],]);
//
//
//        DB::table("tea_images")->insert([
//            ['name' => 'Magic-Kingdom_1000X1000_l.jpg', 'tea_id' => '16'],
//            ['name' => 'magic-kingdom-1000x1000-1.jpg', 'tea_id' => '16'],
//            ['name' => 'Magic-Mango-1000x1000.jpg', 'tea_id' => '16'],
//
//            ['name' => '13148_UshuaiaGingerCitrus_1000X1000_l.jpg', 'tea_id' => '17'],
//
//            ['name' => '13149_BeautyGuarana_1000X1000_l.jpg', 'tea_id' => '18'],
//            ['name' => 'beauty-guarana-1000x1000.jpg', 'tea_id' => '18'],
//            ['name' => '172157981_595420428525238_8277021953584129642_n-1.jpg', 'tea_id' => '18'],
//
//            ['name' => '13008_JasmineDragonPearls_1000x1000_l-1.jpg', 'tea_id' => '19'],
//            ['name' => 'jasmine-dragon-pearls-1000x1000.jpg', 'tea_id' => '19'],
//
//            ['name' => '13044_JasmineChungFengPremiumOrganic_418X418_l-1.jpg', 'tea_id' => '20'],
//            ['name' => '13046_LungChingSecondGradeSuperior_418X418_l-1.jpg', 'tea_id' => '21'],
//            ['name' => '13029_OrganicGunpowder_1000x1000_l.jpg', 'tea_id' => '22'],
//
//            ['name' => '13147_MagicMango_1000X1000_l.jpg', 'tea_id' => '23'],
//            ['name' => 'Magic-Mango-1000x1000.jpg', 'tea_id' => '23'],
//            ['name' => 'travel-tea-kit-1000x1000.png', 'tea_id' => '23'],
//
//            ['name' => '13006_JapanGenmaicha_1000x1000_l.jpg', 'tea_id' => '24'],
//            ['name' => 'BioJapanHojicha_1000X1000_l.jpg', 'tea_id' => '25'],
//        ]);

//        DB::table("tea")->insert([
//            ['name' => 'Special Yellow Sun', 'description' => 'Yellow Tea with aromatic notes that evoke a fresh and delicate floral breeze. We emphasize its peculiar elaboration recovered from an old production process: first the leaves are scalded in high temperature to block the oxidation process, then they are covered with fabrics allowing them to dry slowly until they are completely cooled. This particular elaboration process causes the tea leaves to be yellowish like the infusion. It allows a second infusion at 3 minutes at 80ºC.', 'price' => '713', 'ingredients' => 'Yellow Tea from China', 'type_id' => '3', 'origin_id' => '3']]);
//
//
//        DB::table("tea_images")->insert([
//            ['name' => '17000_SpecialYellowSunTea_1000X1000_l-2.jpg', 'tea_id' => '26'],
//        ]);

//                DB::table("tea")->insert([
//                    ['name' => 'Salted Cream', 'description' => 'Sweet and creamy blend with salted caramel, inspired by the famous Breton recipe. Its moderate sweetness and velvety texture make it perfect for creating creative drinks by adding plant-based beverages and other ingredients such as chocolate, peanut butter, ice cream, or condensed milk. Its moderate caffeine content allows versatility when consuming it. Thanks to its whole leaves, it does not oxidize, making it ideal for enjoying both hot and cold or with ice. An exceptional blend that stands out for its high-quality tea, exclusively made with whole orthodox-style leaves. This blend offers digestive and revitalizing properties, thanks to Chinese Oolong Tea and enriched with a selection of Black Teas certified by the Rainforest Alliance, promoting nature conservation and social standards. Another beneficial ingredient for natural well-being is carob, a legume with a satiating effect.', 'price' => '438', 'ingredients' => 'Oolong Tea, carob, Black Tea, licorice root, cocoa shell, caramel, salt, flavors.', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Italian Panettone', 'description' => 'A new blend within the Tea Dessert family, inspired by the traditional Italian sweet and made with classic ingredients. Made in a soft and silky Oolong Tea base, together with the sweet sultana grape and with a blended sweet citrus flavor. Oolong tea is a semi-rusted tea, which makes it a good ally to combat stomach heaviness and therefore very digestive. Ideal to take hot, and for its low content in theine, throughout the day. The theine content of Oolong Tea (also called Blue Tea) is moderate and inferior to other stimulating plants such as coffee.', 'price' => '488', 'ingredients' => 'Oolong Tea, raisin grapes, citrus peel, lapacho, orange blossom, citrus oil and scents', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Creme Brulee', 'description' => 'The perfect tea for those who love the creamy flavours. The peculiarity of this tea is its high oxidation, which makes the dry colour remind of a black tea. A blend to be enjoyed both in the classic way with 3 minutes of infusion at 85ºC, and at 95ºC and 4 minutes to obtain a more defined sweet taste. An Oolong Tea with long oxidation, low astringency and moderate tannins. With digestive and purifying properties it is advisable to take it after meals or in the afternoon.', 'price' => '438', 'ingredients' => 'Oolong Tea, carob, caramel, cinnamon, vanilla extract and aroma', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Azahar', 'description' => 'Semioxidized Oolong Tea that helps digestion and maintains vitality during the day. The orange blossom accompanies this Oolong Tea very well for its sweet and floral aromatic notes. The theine content of Oolong Tea (also called Blue Tea) is moderate and lower than that of other stimulating plants such as coffee. It is appreciated for its diuretic and digestive properties.', 'price' => '398', 'ingredients' => 'Oolong tea, orange blossom, orange oil, orange arome', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Spicy Strawberry', 'description' => 'Captivating blend of Oolong Tea with spices from Asia and the sweet touch of the strawberry. Oolong Tea is also known as Blue Tea and its digestive effect makes it ideal to enjoy after meals. The theine content of Oolong Tea (also called Blue Tea) is moderate and lower than that of other stimulating plants such as coffee. It is appreciated for its diuretic and digestive properties.', 'price' => '438', 'ingredients' => 'Oolong Tea, Green Tea, carob, ginger, cinnamon, split star anise, pineapple, clove, strawberry, cornflower petals and aromas', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Milky Oolong', 'description' => 'High quality tea, characteristic of China. The dairy flavouring is added to the fresh leaves using a special technique at source, and then subjected to a short oxidation process. We will enjoy an oolong tea with a sweet flavour that reminds us of milk, although it does not contain lactose or derivatives. Its digestive properties make it perfect for all-day consumption. The theine content of Oolong Tea (also called Blue Tea) is moderate and lower than that of other stimulating plants such as coffee. It is appreciated for its diuretic and digestive properties.', 'price' => '419', 'ingredients' => 'Oolong Tea from China, aroma', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Dong Ding', 'description' => 'Variety of Oolong Tea from the highlands of Taiwan, from the Dong Ding mountains (Frozen Peaks). This region produces excellent quality teas due to its fertile soil and humid climate produce a tender and fragrant Oolong Tea. The leaves are green and rolled, oxidation is minimal and the body is light and fresh with sweet fruity notes. No astringency and little theine. As it is a high quality Oolong, it allows multiple infusions: the first for 3 minutes at 90º and the second, also for 3 minutes, but lowering the temperature to 80º. The Oolong Tea (also called Blue Tea) has a moderate theine content, lower than that of other stimulant plants such as coffee. It is appreciated for its diuretic and digestive properties.', 'price' => '382', 'ingredients' => 'Oolong Tea from Taiwan', 'type_id' => '4', 'origin_id' => '3'],
//                    ['name' => 'Tie Kuan Yin', 'description' => 'One of the most appreciated Oolong teas in China, also known as Blue Tea. Its sweet and toasted aroma and its digestive effect make it a delicacy to enjoy after meals. The theine content of Oolong Tea (also called Blue Tea) is moderate and lower than that of other stimulating plants such as coffee. It is appreciated for its diuretic and digestive properties.', 'price' => '398', 'ingredients' => 'Oolong tea from Fujian (China).', 'type_id' => '4', 'origin_id' => '3'],
//                    ]);
//
//                DB::table("tea_images")->insert([
//                    ['name' => '1211_SaltedCaramel_1000X1000_l.jpg', 'tea_id' => '27'],
//                    ['name' => 'saltedcaramel-1000x1000.jpg', 'tea_id' => '27'],
//
//                    ['name' => '12109_ItalianPanetone_1000X1000_l.jpg', 'tea_id' => '28'],
//                    ['name' => '26-12-1000x1000-2.jpg', 'tea_id' => '28'],
//                    ['name' => 'panettone-1000x1000.jpg', 'tea_id' => '28'],
//
//                    ['name' => '12108_CremeBrulee_1000x1000_l.jpg', 'tea_id' => '29'],
//                    ['name' => '12102_AzaharOolong_1000x1000_l.jpg', 'tea_id' => '30'],
//
//                    ['name' => '12106_SpicyStrawberry_1000x1000_l.jpg', 'tea_id' => '31'],
//                    ['name' => 'spicy-strawberry-1000x1000.jpg', 'tea_id' => '31'],
//
//                    ['name' => '12004_MilkyOolongOriginChina_1000X1000_l-1.jpg', 'tea_id' => '32'],
//                    ['name' => '12007_DongDingOolongLeafTea_1000X1000_l.jpg', 'tea_id' => '33'],
//                    ['name' => '12003_TieKuanYin_1000x1000_l.jpg', 'tea_id' => '34'],
//                ]);

//        DB::table("tea")->insert([
//            ['name' => 'Snow Christmas', 'description' => 'The expression "beauty" of Christmas of sweet and creamy taste that evokes the classic caramelised baked apple tart. Ideal to enjoy in a festive and cosy winter. Its delicate and sweet aroma is an invitation to the well-being that cradles the magnificent properties of White Tea, considered the beauty tea par excellence. It provides antioxidants, is purifying and diuretic. ', 'price' => '597', 'ingredients' => 'White Tea, manzana, mango, caramel, Roman chamomile, aroma', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Gracia Blend', 'description' => 'Gracia Blend White with its delicate flavor catches any palate and makes you fly to the origins of Tea Shop. It is the Gracia Blend in its most elegant aromatic expression. The silky, light character of White Tea is balanced by the enveloping sweetness of vanilla and flowers. Its ingredients elegantly combine the modernist origins of the city of Barcelona and markedly Mediterranean notes. White Tea for its properties are defined as tea of beauty. It is made from the first three leaves of the plant, with the unopened bud and its layer of "white fluff", which gives the name to this variety. The leaves without rusting wither and dry by hand, preserving all the flavor and properties of the plant. It is the most select and distinguished category for its maximum contribution of antioxidants.', 'price' => '652', 'ingredients' => 'White Tea, orange peel, cornflower petals, red rose petals, sunflower petals, vanilla, flavourings', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Pai Mu Tan', 'description' => 'White Tea known as Pai Mu Tan or White Peony, famous for its fine floral aroma. This exclusive tea is harvested by hand and only the buds and the first two tender leaves are used. It is a very appreciated traditional Chinese tea with a very limited production. Due to its delicacy, the infusion of White Tea oxidizes quickly, so we recommend its consumption within two hours of preparation. White Tea is the quintessential beauty tea. It provides antioxidants, is depurative and diuretic.', 'price' => '530', 'ingredients' => 'White Tea from Fujian', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Sakura Beauty', 'description' => 'A different and original mixture, which loyalty to the most loving palates of unique flavors. An alchemy of flavors to purify. White tea provides beautifying properties, while green tea and matcha tea act as powerful antioxidants and diuretics. Rose buds help with digestion after meals.', 'price' => '530', 'ingredients' => 'White Tea, Green Tea, Matcha Tea, apple, ALMOND, kiwi, rose buds, Morello cherry, cornflower petals, flavourings', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Strawberry Fresh', 'description' => 'An ideal mixture for those looking for a good taste but with little theine. Its young and fresh character captivates the "healthiest" palates. Due to its delicacy, the white tea infusion quickly oxidizes, so it is recommended that it be consumed within two hours of its preparation, with the exception of when it is prepared in the "Ice Tea" style, in which the tea enters in contact with ice and stops its oxidation process. White Tea is the tea of beauty par excellence. Pai Mu Tan is made with the most tender bud and the two leaves that follow. It provides antioxidants, is purifying and diuretic.', 'price' => '652', 'ingredients' => 'White tea, apple, pineapple (pineapple, sugar), rosehip peel, basil, strawberry and flavorings', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'White Kiss', 'description' => 'A mixture for lovers of pure teas and delicate flavors. The exclusive Pai Mu Tan tea is collected manually and only the buds and the first two young leaves are used. It is a highly appreciated traditional Chinese tea with very limited production. Due to its delicacy, the white tea infusion quickly oxidizes, so its consumption is recommended within two hours of its preparation. White Kiss is a very successful base to prepare a delicious and elegant cocktail with Cava or Champagne very cold. White Tea is the tea of beauty par excellence. Pai Mu Tan is made with the most tender bud and the two leaves that follow. It provides antioxidants, is purifying and diuretic.', 'price' => '691', 'ingredients' => 'White Tea (Pai Mu Tan), strawberry, wild strawberry leaves and aroma', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Silver Needles', 'description' => 'The Silver Needles is produced in small quantities. It is only composed of velvety sprouts. These leaves are only withered and dried, to preserve a very natural appearance and final aroma. Due to its delicacy, the infusion of the Silver Needles sprouts oxidize quickly, so we recommend its consumption within two hours of preparation. We recommend scalding the teapot or cup where the tea is prepared first, so that the buds open up and give off all their splendour. The Silver Needles is the beauty tea par excellence and is only made with the most tender bud. It provides antioxidants, it is depurative and diuretic.', 'price' => '1018', 'ingredients' => 'White Tea from Yunnan', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Ya Bao Silver Buds', 'description' => 'Distinguished wild white tea of Yunnan with velvety spring sprouts. Only the wisdom of a millenary tradition like the Chinese could achieve such a special tea. Its name "Ya Bao" means "spring sprouts", the time when the tea is harvested to give it an aroma reminiscent of ripe fruit and spring flowers. The pale yellow, velvety sprouts are hand-picked in early spring with special care and delicacy to prevent damage and oxidation. Afterwards, the sprouts wither slightly and dry naturally. Surprisingly, the faint colour of the infusion is almost imperceptible in contrast to the fragrant aroma that awakens on the palate. The ripe fruit notes are reminiscent of white gooseberry, with a final bouquet of white flowers. A cup of tea to enjoy in moments of complete relaxation and in the company of a good book. White tea is considered the beauty tea par excellence thanks to its high antioxidant content. It is also highly depurative and diuretic.', 'price' => '610', 'ingredients' => 'White Tea', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Fresh Melon', 'description' => 'The most refreshing and summery mix thanks to the melon flavour and the refined freshness of White Tea with Green Tea, pineapple, apple, melon and marigold petals. White Tea is known as beauty tea, for its high content of antioxidants and its low level of theine.', 'price' => '554', 'ingredients' => 'White Tea, Green tea, pineapple, apple, melon, marigold petals, flavouring', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'Sunny Peach', 'description' => 'Refreshing blend ideal as "Ice Tea" with White and Green Tea, peach and a touch of pear. It has a velvety and very light texture, which makes it a drink that can accompany you throughout the day. Ideal to start in the world of "Ice Tea", it has a sweet and fruity taste. The combination of White Tea, Green Tea and fruits are ingredients with antioxidant and diuretic properties.', 'price' => '554', 'ingredients' => 'White tea, Green Tea, apple, rose hip seeds, pear, peach, cornflower petals, marigold petals, aromas', 'type_id' => '5', 'origin_id' => '3'],
//            ['name' => 'White Daiquiri', 'description' => 'The most famous summery cocktai, a flavor explosion in combination of White Tea and exotic fruits, with apple, coconut, pineapple, blackberry leaves and lime oil. Although it is White Tea, which is usually best drunk on its own, in this case a touch of vegetable drink will add creaminess and will remind us of the cocktail that inspired it. White Tea is known as beauty tea, for its high content of antioxidants and its low level of theine.', 'price' => '554', 'ingredients' => 'White tea, apple, coconut, pineapple (pineapple, sugar), blackberry leaves, coco flavour and lime oil', 'type_id' => '5', 'origin_id' => '3'],
//         ]);
//
//        DB::table("tea_images")->insert([
//            ['name' => '14014_snow_christmas_1000X1000.jpg', 'tea_id' => '35'],
//            ['name' => 'Te-n-4-snow-christmas-1000x1000.jpg', 'tea_id' => '35'],
//
//            ['name' => '14005_GraciaWhiteBlend_1000x1000_l.jpg', 'tea_id' => '36'],
//            ['name' => '14001_PauMuTan_1000x1000.jpg', 'tea_id' => '37'],
//            ['name' => '14017_SakuraBautyBlend_1000X1000_l.jpg', 'tea_id' => '38'],
//            ['name' => '14013_StrawberryFresh_1000x1000_l.jpg', 'tea_id' => '39'],
//            ['name' => '14003_WhiteKiss_1000x1000_l.jpg', 'tea_id' => '40'],
//            ['name' => 'te-blanco-white-kiss-1000x1000.jpg', 'tea_id' => '40'],
//            ['name' => '14007_SilverNeedlesBaiHaoYinZhen_418x418_m.jpg', 'tea_id' => '41'],
//            ['name' => '14019_YaBaoSilverBudsWhiteTeaChina_1000X1000_l-.jpg', 'tea_id' => '42'],
//
//            ['name' => '14011_FreshMelon.jpg', 'tea_id' => '43'],
//            ['name' => 'fresh-melon-1000x1000-3.jpg', 'tea_id' => '43'],
//            ['name' => 'fresh-melon-1000x1000-2-1.jpg', 'tea_id' => '43'],
//            ['name' => 'Fresh-Melon-1000x1000.jpg', 'tea_id' => '43'],
//
//            ['name' => '14016_PeachySplash_1000X1000_l-1.jpg', 'tea_id' => '44'],
//            ['name' => 'sunny-1000x1000.jpg', 'tea_id' => '44'],
//            ['name' => 'Sunny-Peach-1000x1000.jpg', 'tea_id' => '44'],
//            ['name' => 'sunny-peach-smootea-1000x1000.jpg', 'tea_id' => '44'],
//
//            ['name' => '14012_WhiteDaiquiri.jpg', 'tea_id' => '45'],
//            ['name' => 'White-Daiquiri-1000x1000.jpg', 'tea_id' => '45'],
//        ]);

//        DB::table("tea")->insert([
//            ['name' => 'Pu Erh Christmas', 'description' => 'ChristmasTea Red from our range of Christmas teas and infusions, is a blend with more than 20 years of history and is still made with the same old recipe. With vegetable drink it reminds us of the delicious marzipan. Available in the varieties Black, Red and Rooibos. Red Tea and spices help to purify by eliminating toxins and fats, they are a great ally of the digestive process. ', 'price' => '379', 'ingredients' => 'Pu Erh Red Tea, ALMOND, orange, apple, cinnamon, clove, cornflower petals, orange oil, aroma', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Ashwagandha Elixir', 'description' => 'Enjoy the warm flavor with a touch of sweet cinnamon that turns this blend into a delight for the palate. To make the most of the benefits of this blend, we recommend enjoying several cups of Pu Erh Ashwagandha Elixir throughout the day, consistently over time. It can be prepared with plant-based milk to provide a creamy texture and exceptional taste. The Red Pu Erh Tea, known as the "Tea of Health" in traditional Chinese medicine, acts on the energies that regulate the body. Consuming three cups a day can improve the functioning of the body, promoting its purifying and slimming effects. On the other hand, ashwagandha, also known as Indian ginseng, is a fundamental herb in Ayurveda for its wide-ranging health benefits. Its roots are used in various forms, including in tea. In addition to hydration, ashwagandha nourishes health and well-being, promoting resilience and calmness simultaneously, strengthening the nervous system, and promoting restful sleep. This herb, native to India and cultivated worldwide, is an invaluable ally for facing stress and maintaining a balanced body.', 'price' => '529', 'ingredients' => 'Special fermentation Red Pu Erh Tea, Black Tea, rosehip seeds, cinnamon, Ashwagandha root, cloves, pink pepper, and natural flavors.', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Slim Puccinotea', 'description' => 'A perfect tea for breakfast and snacks. Combined with milk or a vegetable drink, it will make lovers of the popular Cappuccino fall in love. All the creaminess of caramel in a cup of Buenos Dias! A mixture with the purifying virtues of Pu Erh Red Tea and the energy contribution of Black Tea.', 'price' => '447', 'ingredients' => 'Pu Erh Red Tea, Black Tea, caramel bits, flavouring.', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Choco Turron', 'description' => 'An irresistible and cheerful combination of chocolate and puffed rice, enriched with delicious Pu Erh Red Tea. A tea to enjoy at breakfast and snacks, only, with milk or vegetable drink. Besides being a whim, it is a delicious way to hydrate yourself during the day. Pu Erh is a tea with a low content of theine and is a special fermentation tea with purifying, antioxidant and anti-inflammatory properties that helps improve digestion after meals.', 'price' => '433', 'ingredients' => 'Pu Erh Red Tea, carob, cocoa shell, puffed rice, cocoa beans, chocolate, aroma', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Choconoir', 'description' => 'A pleasant blend designed to satisfy the lovers of the most intense chocolate: we have created this mixture with the unique flavor of highly purifying Pu Erh red tea, lapacho bark with vanilla taste, cocoa shell, cocoa beans and sweet chocolate chips. All the pleasure of chocolate without calories. Pu Erh and lapacho facilitate digestion and regulate intestinal transit, they favour the elimination of unwanted substances from our body, increase physical, intellectual performance and immune system reaction. Pu Erh is a tea with low theine content, of special fermentation and with depurative, antioxidant and digestive properties.', 'price' => '455', 'ingredients' => 'Pu Erh Red Tea, cocoa shell, cocoa, lapacho, chocolate, aroma.', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Pu Erh Chai', 'description' => 'Pu Erh Red Tea undergoes a special fermentation that gives it the characteristic earthy taste. Well-being and pleasure come together in Pu Erh and thanks to the spices we add ayurvedic properties. It is considered "the tea of health", since according to the traditional Chinese medicine, it acts on the energies that regulate the functions of the body. The aim of Chinese medicine is not so much to cure as to prevent. Pu Erhs "three cups a day" plan will facilitate the proper functioning of the body. The Red Tea acts as an accelerator of the hepatic function so it helps to eliminate the toxins and fats accumulated in the blood', 'price' => '467', 'ingredients' => 'Pu Erh Red Tea, cinnamon, ginger, clove, cardamom seeds', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Vanilla Bellini', 'description' => 'Its captivating taste transports us to the famed cocktail in Harrys Bar in Venice. Red Tea taken daily helps to purify you and is a good ally for digestion after meals. Suitable for drinking both hot and cold. A blend from the detox line with all the properties of Pu Erh: digestive, cleansing, diuretic. ', 'price' => '445', 'ingredients' => 'Pu Erh Red Tea, carob, apple, pomegranate seeds, linseed, peach, catsfood, Roman chamomile, vanilla extract and aroma.', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Red Curcuma Latte', 'description' => 'An ideal mix to enjoy every day of unique flavors that favor the welfare of our body. It contains the ingredients of the thousand virtues: Pu Erh Red Tea, turmeric and ginger. Ideal infused with a touch of pepper to enhance its properties. With vegetable drink its creaminess is boosted. Pu Erh is a specially fermented tea with a low content in theine. Turmeric and ginger belong to the same botanical family and are classified as superfoods. In Ayurvedic medicine, together with spices, they have always been used for their beneficial properties: they aid digestion, lower cholesterol and are antioxidants.', 'price' => '498', 'ingredients' => 'Pu Erh Red Tea, carob, raisin, ginger, turmeric, COCONUT, star anise, pistachio, aroma', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Tearamisu', 'description' => 'Tearamisú, an Italian story where the noble dessert of tradition transforms into tea, with its characteristic sweetness and flavor. This exquisite blend combines healthy ingredients such as Pu Erh Red Tea, chicory root, Rooibos, cocoa, and coffee, creating a symphony of aromatic notes that range from sweet to bitter. The versatility of this tea allows for the creation of multiple recipes, whether brewed hot or cold, and with the addition of a variety of ingredients like milk, plant-based milk, ice cream, mascarpone, or other creamy options. A blend with the detoxifying virtues of Pu Erh Red Tea and chicory root, combined with the isotonic property of Rooibos.', 'price' => '505', 'ingredients' => 'Special fermentation Pu Erh Red Tea, chicory root, cocoa peel, BARLEY, Black Tea, Rooibos, cocoa powder, white chocolate, coffee beans, and flavorings.', 'type_id' => '6', 'origin_id' => '3'],
//            ['name' => 'Cinnamon Roll', 'description' => 'Delicious blend inspired by the famous 1920s dessert "Cinnamon Roll", with a more intense touch of cocoa. Ideal to enjoy at any time of the day, with or without a vegetable drink. A plan of 3 cups a day helps the bodys depurative process. Pu Erh is a Tea with low content of theine and special fermentation with purifying, antioxidant and also digestive properties, properties that can also be found in cinnamon and turmeric. ', 'price' => '520', 'ingredients' => 'Pu Erh Red Tea, cocoa shell, apple, cinnamon, cocoa, carob, turmeric, rose petals and marigold, aroma.', 'type_id' => '6', 'origin_id' => '3'],
//        ]);
//
//        DB::table("tea_images")->insert([
//            ['name' => '11104_ChristmasTeaRed_1000x1000_l-1.jpg', 'tea_id' => '46'],
//            ['name' => '11123_AshwagandhaElixir_1000X1000_l.jpg', 'tea_id' => '47'],
//            ['name' => 'ashwagandha-1000x1000-1.jpg', 'tea_id' => '47'],
//            ['name' => 'ashwagandha-1000x1000.jpg', 'tea_id' => '47'],
//            ['name' => '11112_SlimPuccinoTea_1000x1000_l.jpg', 'tea_id' => '48'],
//            ['name' => '10164_ChocoTurron_1000x1000.jpg', 'tea_id' => '49'],
//            ['name' => '1000x1000-choco-turron.jpg', 'tea_id' => '49'],
//            ['name' => 'chocoturron-1000x1000-1.jpg', 'tea_id' => '49'],
//            ['name' => '11113_PuErhChocoNoir_1000x1000_l.jpg', 'tea_id' => '50'],
//            ['name' => '02---Pu-Erh-ChocoNoir-con-chocolates-04-1.jpg', 'tea_id' => '50'],
//            ['name' => '11109_PuErhChai_1000x1000_l.jpg', 'tea_id' => '51'],
//            ['name' => 'pu-erh-chai-1000x1000.jpg', 'tea_id' => '51'],
//            ['name' => '11116_VanillaBellini_1000X1000_l-.jpg', 'tea_id' => '52'],
//            ['name' => 'Vanilla-Bellini-1000x1000-jpeg.jpg', 'tea_id' => '52'],
//            ['name' => '11118_RedCurcumaLatte_1000X1000_l.jpg', 'tea_id' => '53'],
//            ['name' => 'RED-CURCUMA-LATTE-1000x1000.jpg', 'tea_id' => '53'],
//            ['name' => '11122_Tearamisu_1000X1000_l.jpg', 'tea_id' => '54'],
//            ['name' => 'tearamisu-1000x1000-1.jpg', 'tea_id' => '54'],
//            ['name' => 'tearamisu-1000x1000.jpg', 'tea_id' => '54'],
//            ['name' => '11117-TeaGranelCinnamonRoll_1000X1000_l.jpg', 'tea_id' => '55'],
//            ['name' => 'cinnamon-1000x1000.jpg', 'tea_id' => '55'],
//        ]);

//        DB::table("tea")->insert([
//            ['name' => 'Organic Matcha', 'description' => 'Ground Green Tea from Japanese organic agriculture, for your daily intake of antioxidants. The carefully hand-picked tea leaves are ground in a stone mill until they reach their fine texture. All Japanese Matchas require special care in their production, starting with the pruning of the Camellia Sinensis (the supply of nutrients) and ending with the harvesting. Thanks to its powdery texture, it is very versatile and can be consumed in many different ways. HOW TO PREPARE YOUR ORGANIC MATCHA TEA: with a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake until a thin layer of foam is created, pour into a glass of water at 80-95ºC. Enjoy with the addition of your favourite vegetable drink or milk. A cup of Matcha contributes to mental balance, concentration and a general feeling of well-being to start the day with energy.', 'price' => '1019', 'ingredients' => 'Ground Matcha Green Tea', 'type_id' => '7', 'origin_id' => '5'],
//            ['name' => 'Choco Vanilla', 'description' => 'The Matcha Latte Chocolate & Vanilla with its intense cocoa flavor and the floral touch of vanilla is ideal for enjoying hot or cold. Flavored Matchas are ideal to make recipes. There are many sweet and savoury dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE CHOCOLATE & VANILLA TEA: with a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and diuretic, with extra theine.', 'price' => '691', 'ingredients' => 'Matcha Green Tea, cocoa aroma', 'type_id' => '7', 'origin_id' => '5'],
//            ['name' => 'Latte Mango', 'description' => 'Green Matcha Tea with the sweet taste of mango. Flavored Matches are ideal to make recipes. There are many sweet and salty dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE MANGO TEA: With a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy it by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and diuretic, with extra theine.', 'price' => '691', 'ingredients' => 'Matcha Green Tea, aroma', 'type_id' => '7', 'origin_id' => '5'],
//            ['name' => 'Latte Chai', 'description' => 'Match Green Tea with Chai spices, perfect for smoothies and healthy recipes. Flavored Matches are ideal for recipes. There are many sweet and salty dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE CHAI TEA: With a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy it by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and is a diuretic with extra theine. Spices give us vitality.', 'price' => '691', 'ingredients' => 'Matcha green tee, cinnamon, cardamom, clef, aroma.', 'type_id' => '7', 'origin_id' => '5'],
//        ]);
//
//        DB::table("tea_images")->insert([
//            ['name' => '13021_OrganicMatcha_1000X1000_l-1.jpg', 'tea_id' => '56'],
//            ['name' => 'matchas-1000x1000.jpg', 'tea_id' => '56'],
//            ['name' => 'organic-matcha-1000x1000.jpg', 'tea_id' => '56'],
//
//            ['name' => '75049_MatchaLatteMango_1000X1000_l.jpg', 'tea_id' => '57'],
//            ['name' => '75062_MatchaLatteChai_1000X1000_l.jpg', 'tea_id' => '58'],
//            ['name' => '75076_MatchaLatteChocoVainilla_1000X1000_l-.jpg', 'tea_id' => '59'],
//
//        ]);

        DB::table("tea")->insert([
            ['name' => 'Organic Matcha', 'description' => 'Ground Green Tea from Japanese organic agriculture, for your daily intake of antioxidants. The carefully hand-picked tea leaves are ground in a stone mill until they reach their fine texture. All Japanese Matchas require special care in their production, starting with the pruning of the Camellia Sinensis (the supply of nutrients) and ending with the harvesting. Thanks to its powdery texture, it is very versatile and can be consumed in many different ways. HOW TO PREPARE YOUR ORGANIC MATCHA TEA: with a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake until a thin layer of foam is created, pour into a glass of water at 80-95ºC. Enjoy with the addition of your favourite vegetable drink or milk. A cup of Matcha contributes to mental balance, concentration and a general feeling of well-being to start the day with energy.', 'price' => '1019', 'ingredients' => 'Ground Matcha Green Tea', 'type_id' => '7', 'origin_id' => '5'],
            ['name' => 'Choco Vanilla', 'description' => 'The Matcha Latte Chocolate & Vanilla with its intense cocoa flavor and the floral touch of vanilla is ideal for enjoying hot or cold. Flavored Matchas are ideal to make recipes. There are many sweet and savoury dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE CHOCOLATE & VANILLA TEA: with a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and diuretic, with extra theine.', 'price' => '691', 'ingredients' => 'Matcha Green Tea, cocoa aroma', 'type_id' => '7', 'origin_id' => '5'],
            ['name' => 'Latte Mango', 'description' => 'Green Matcha Tea with the sweet taste of mango. Flavored Matches are ideal to make recipes. There are many sweet and salty dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE MANGO TEA: With a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy it by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and diuretic, with extra theine.', 'price' => '691', 'ingredients' => 'Matcha Green Tea, aroma', 'type_id' => '7', 'origin_id' => '5'],
            ['name' => 'Latte Chai', 'description' => 'Match Green Tea with Chai spices, perfect for smoothies and healthy recipes. Flavored Matches are ideal for recipes. There are many sweet and salty dishes made with Matcha: ice creams, cocktails, fruit and vegetable smoothies and many more. HOW TO PREPARE YOUR MATCHA LATTE CHAI TEA: With a bamboo spoon, pour 1.5-2 g of tea and water at room temperature into a Matcha Shaker. Shake to create a thin layer of foam, pour into a glass of water at 80-95ºC. Enjoy it by adding your favorite vegetable drink or milk. Matcha is a source of antioxidants and is a diuretic with extra theine. Spices give us vitality.', 'price' => '691', 'ingredients' => 'Matcha green tee, cinnamon, cardamom, clef, aroma.', 'type_id' => '7', 'origin_id' => '5'],
        ]);

        DB::table("tea_images")->insert([
            ['name' => '13021_OrganicMatcha_1000X1000_l-1.jpg', 'tea_id' => '56'],
            ['name' => 'matchas-1000x1000.jpg', 'tea_id' => '56'],
            ['name' => 'organic-matcha-1000x1000.jpg', 'tea_id' => '56'],

            ['name' => '75049_MatchaLatteMango_1000X1000_l.jpg', 'tea_id' => '57'],
            ['name' => '75062_MatchaLatteChai_1000X1000_l.jpg', 'tea_id' => '58'],
            ['name' => '75076_MatchaLatteChocoVainilla_1000X1000_l-.jpg', 'tea_id' => '59'],

        ]);

    }
}
